### ISSUE TITLE
[Bug]-Chat not working properly

### ISSUE THREAD

**Issue by Khanak21** [Khanak21/Whiteboard#2]
The issue in chat is when a person writes a message, the other person receives it multiple times, and not a single time ,and the number of messages keeps multiplying each time someone sends a message to other

**Comment by adarshjhaa100** [comment]
Hello @Khanak21 can you please attach a screenshot if possible. Meanwhile i'm trying to run your app on local

**Comment by Khanak21** [comment]
Yeah sure
This is the presenter side
<img width="960" alt="image" src="https://github.com/Khanak21/Whiteboard/assets/127039986/7bdb3a95-8303-4ffe-92aa-c3918ae43943">
This is the non presenter side
<img width="960" alt="image" src="https://github.com/Khanak21/Whiteboard/assets/127039986/6adad874-ac86-4af4-9b06-a0113f1b3b3d">
As you can see,the non presenter's messages are not visible to the presenter and the presenter's message gets sent multiple times

**Comment by Khanak21** [comment]
There was a problem with connection i guess in the above image that's why you cannot see non presenter's messages
but after i fixed it, there's another issue that the sender's name is not visible in chat instead it shows the room code
<img width="951" alt="image" src="https://github.com/Khanak21/Whiteboard/assets/127039986/922a312e-0553-4efb-94a1-c02fababb814">
But still,the problem of repetition of sent messages persist

**Comment by adarshjhaa100** [comment]
Hello @Khanak21 , I've found the issue. the socket.on method registers listeners corresponding to an event. In the ChatBar component, the event messageResponse is getting registered in useEffect:
![image](https://github.com/Khanak21/Whiteboard/assets/31096082/18d6b5f1-ef94-4a3b-a77b-33a2d5ceaad3)

Everytime the useEffect runs, it will register the event thus creating multiple copies. You can check this by displaying socket._callbacks:
![image](https://github.com/Khanak21/Whiteboard/assets/31096082/2edf648b-807a-4826-8153-079d8016af9d)

I've noticed that you've added a cleanup socket.off(), but it doesn't seem to be working. This could easily be resolved by registering the listener exactly once by the usual trick of setting useState dependency to empty array.
![image](https://github.com/Khanak21/Whiteboard/assets/31096082/1f4f4a23-52bd-4fca-882f-7f8510cad80f)

![image](https://github.com/Khanak21/Whiteboard/assets/31096082/332b95e3-5c63-47a1-82d6-6aa6667aaf6b)

If you want I can raise a PR for this fix

**Comment by adarshjhaa100** [comment]
The sender's name is visible for me you know. But I think sometimes when you hot-reload your code, there might be some issues with the webSocket connection, you should try console logging the username when you receive the message. I think you can create a separate bug for this.

Btw, there could be some styling fixes here and there. But, the project looks good overall. One suggestion is that you can add auto-smoothing when you're drawing with the pencil.

**Comment by Khanak21** [comment]
Thank you so much! Really appreciate your help. Sure you can raise a PR, I'll then review and merge it. Can you suggest how can I implement auto-smoothing?

**Comment by adarshjhaa100** [comment]
I've raised the PR. For line smoothing there are various algorithms in Computer Graphics but there's a cool library that you can use : https://github.com/dulnan/lazy-brush

**Comment by Khanak21** [comment]
I have merged it. Thanks for your contribution! I'll close the issue now
If you want to contact me, you can connect on linkedin: https://www.linkedin.com/in/khanak-patwari/
